[functions]
  directory = "netlify/functions"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assetlinks-android.json"
  status = 200
